version: "3.9"

services:
  app:
    container_name: pingaroo
    build:
      context: .
      dockerfile: Dockerfile
    command: tail -F somethingsomething
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=local_settings
    volumes:
      - .:/app

  redis:
    container_name: redis
    image: redis:latest
    ports:
      - "6379:6379"
    command: redis-server --loglevel warning --requirepass foobar
    volumes:
      - cache:/data

volumes:
  cache:
    driver: local
