# Generated by Django 4.2.5 on 2023-09-22 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MonitorTarget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='MonitorResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_down', models.BooleanField()),
                ('latency', models.DecimalField(decimal_places=3, max_digits=5)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pingaroo.monitortarget')),
            ],
        ),
    ]
