# Generated by Django 4.2.5 on 2023-09-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pingaroo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitorresult',
            name='latency',
            field=models.IntegerField(null=True),
        ),
    ]
